# baseURL = "https://computer-union.jp/
baseURL = "https://computerunionjp.github.io/"
locale = "ja"
title = "コンピュータ・ユニオン"
contentDir = "src"
publishDir = "_site"

[markup.goldmark.renderer]
unsafe = true
