# baseURL = "https://computer-union.jp/
baseURL = "https://computerunionjp.github.io/"
locale = "ja"
timeZone = 'Asia/Tokyo'
title = "コンピュータ・ユニオン"

[taxonomies]
# category -- disabled
# tag -- disabled

[markup.goldmark.renderer]
unsafe = true

[outputFormats.rss]
baseName = "rss"

[params]
# contact_url = "https://docs.google.com/forms/d/e/1FAIpQLSdt5ehYnkFv5l23B6YwKp4h0hOWCl6UblMoYIGk_OStKkfdVQ/viewform?usp=header"
contact_url = "https://computer-union.jp/?page_id=4650"
